apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: wallet
  labels:
    app.kubernetes.io/name: digital-wallet
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  JWT_SECRET: "replace-with-secret"
  JWT_REFRESH_SECRET: "replace-with-secret"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_USER: "replace-email"
  EMAIL_PASS: "replace-app-password"
  RAZORPAY_KEY_ID: ""
  RAZORPAY_KEY_SECRET: ""
  RAZORPAY_WEBHOOK_SECRET: ""
