apiVersion: v1
kind: Service
metadata:
  name: wallet-backend
  namespace: wallet
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
spec:
  selector:
    app: wallet-backend
  ports:
    - name: http
      port: 5000
      targetPort: http
  type: ClusterIP
