apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: wallet
  labels:
    app.kubernetes.io/name: digital-wallet
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: digital-wallet
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 5000
      targetPort: http
