apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-frontend
  namespace: wallet
  labels:
    app: wallet-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wallet-frontend
  template:
    metadata:
      labels:
        app: wallet-frontend
    spec:
      containers:
      - name: frontend
        image: nitishchy12/wallet-frontend:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
