apiVersion: v1
kind: Service
metadata:
  name: wallet-frontend
  namespace: wallet
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  selector:
    app: wallet-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
