// Purpose: Generate PDF receipt for a transaction with HMAC verification code
// Dependencies: pdfkit, crypto
// Used by: backend/controllers/walletController.js (downloadReceipt)

const PDFDocument = require('pdfkit');
const crypto = require('crypto');

const generateVerificationCode = (transactionId, amount, timestamp) => {
  const secret = process.env.RECEIPT_SECRET || process.env.JWT_SECRET || 'receipt-secret';
  const payload = `${transactionId}:${amount}:${timestamp}`;
  return crypto.createHmac('sha256', secret)
    .update(payload)
    .digest('hex')
    .substring(0, 16)
    .toUpperCase();
};

const generateReceipt = (transaction, senderName, receiverName) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const verificationCode = generateVerificationCode(
      transaction._id.toString(),
      transaction.amount,
      transaction.createdAt.toISOString()
    );

    // ── Header ──────────────────────────────────────────────────────────────
    doc.fontSize(24).font('Helvetica-Bold').text('Digital Wallet', { align: 'center' });
    doc.fontSize(14).font('Helvetica').text('Transaction Receipt', { align: 'center' });
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown(0.5);

    // ── Transaction details ──────────────────────────────────────────────────
    // Type label — Transaction schema has TRANSFER, DISPUTE_REVERSAL, ADD_MONEY etc.
    const typeLabel = {
      TRANSFER: 'Transfer Sent',
      DISPUTE_REVERSAL: 'Dispute Reversal',
      ADD_MONEY: 'Money Added'
    }[transaction.type] || transaction.type;

    const details = [
      ['Transaction ID', transaction.transactionId || transaction._id.toString()],
      ['Date',           new Date(transaction.createdAt).toLocaleString('en-IN')],
      ['Type',           typeLabel],
      ['From',           senderName],
      ['To',             receiverName],
      ['Amount',         `Rs ${transaction.amount.toLocaleString('en-IN')}`],
      ['Status',         transaction.status],
      ['Description',    transaction.description || 'N/A']
    ];

    // Include balance snapshot if present (set by transferMoney controller)
    if (transaction.balanceSnapshot?.senderBalance != null) {
      details.push(['Sender Balance After', `Rs ${transaction.balanceSnapshot.senderBalance.toLocaleString('en-IN')}`]);
    }
    if (transaction.balanceSnapshot?.receiverBalance != null) {
      details.push(['Receiver Balance After', `Rs ${transaction.balanceSnapshot.receiverBalance.toLocaleString('en-IN')}`]);
    }

    details.forEach(([label, value]) => {
      doc.fontSize(11).font('Helvetica-Bold').text(`${label}: `, { continued: true });
      doc.font('Helvetica').text(value);
    });

    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown(0.5);

    // ── Verification code ────────────────────────────────────────────────────
    doc.fontSize(10).font('Helvetica').text('Verification Code (contact support to verify):', { align: 'center' });
    doc.fontSize(14).font('Helvetica-Bold').text(verificationCode, { align: 'center' });
    doc.moveDown(0.5);

    doc.fontSize(9).font('Helvetica').fillColor('grey').text(
      'This receipt was generated by Digital Wallet System. ' +
      'The verification code can be validated by our support team.',
      { align: 'center' }
    );

    doc.end();
  });
};

module.exports = { generateReceipt, generateVerificationCode };
